# Generated by Django 4.0.4 on 2022-05-24 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('maximum_stake', models.PositiveIntegerField(default='000000', null=True)),
                ('minimum_stake', models.PositiveIntegerField(default='000.00', null=True)),
                ('roi', models.PositiveIntegerField()),
                ('duration', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.PositiveIntegerField(null=True)),
                ('amount', models.PositiveIntegerField(default='000.00', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Unactive')], max_length=20)),
                ('balance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.balance')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
